### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by marll** [apioo/fusio-sample-cms#1]
Hi,
after the following command
 php bin/fusio deploy

the output is:
- [UPDATED] config Changed 2 values
- [CREATED] schema Page
- [CREATED] schema Post
- [CREATED] schema Message
- [CREATED] schema Page-Collection
- [CREATED] schema Post-Collection
- [CREATED] action App_Action_Page_Collection
- [CREATED] action App_Action_Page_Create
- [CREATED] action App_Action_Page_Entity
- [CREATED] action App_Action_Page_Update
- [CREATED] action App_Action_Page_Delete
- [CREATED] action App_Action_Post_Collection
- [CREATED] action App_Action_Post_Create
- [CREATED] action App_Action_Post_Entity
- [CREATED] action App_Action_Post_Update
- [CREATED] action App_Action_Post_Delete
- [FAILED] routes /page: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- [FAILED] routes /page/:page_id: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- [FAILED] routes /post: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- [FAILED] routes /post/:post_id: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- [CREATED] event page_created
- [CREATED] event page_updated
- [CREATED] event page_deleted
- [CREATED] event post_created
- [CREATED] event post_updated
- [CREATED] event post_deleted

Deploy contained 4 errors!

- /page: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- /page/:page_id: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- /post: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286
- /post/:post_id: Undefined offset: 200 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\fusio-sample-cms-master\vendor\psx\schema\src\SchemaTraverser.php on line 286

thanks

**Comment by chriskapp** [comment]
Hi, this is probably a problem regarding your PHP version. You need at least PHP 7.2. We have also automated tests which run the deployment automatically https://travis-ci.org/github/apioo/fusio-sample-cms and all builds are fine.

**Comment by marll** [comment]
Ok, now work.
Thanks
