### ISSUE TITLE
Error after deploying

### ISSUE THREAD

**Issue by paitoncamp** [apioo/fusio-sample-cms#4]
I got this error after deploying 

> Fatal error: Uncaught Error: Class 'PSX\Framework\Environment\WebServer\Engine' not found in D:\xampp\htdocs\fusio-sample-cms\public\index.php:26 Stack trace: #0 {main} thrown in D:\xampp\htdocs\fusio-sample-cms\public\index.php on line 26

what is going wrong?

**Comment by chriskapp** [comment]
Hi, it sounds like you have not executed `composer install` to install all dependencies through the composer packagemanager.

**Comment by paitoncamp** [comment]
I did that already. Is it possible that it has something related with the fusio framework version?

**Comment by chriskapp** [comment]
Yes this could be also a reason, please try to remove the `composer.lock` file and then run `composer install` again, through this you will obtain the latest versions of the dependencies.

**Comment by chriskapp** [comment]
FYI I have also just updated the `composer.lock` file so that we use the correct dependencies.

**Comment by paitoncamp** [comment]
Its still doesn't work for me :(   but I try to move it to the latest fusio framework installed and working fine.

**Comment by chriskapp** [comment]
I will close this issue since it looks like the issue is solved, otherwise please open another issue.
